set(time 0)
set(preset 1)
set(mode --shot)
if(SCENE STREQUAL "aircraft")
  set(mode --intro-shot)
  set(time 2)
elseif(SCENE STREQUAL "release")
  set(mode --intro-shot)
  set(time 5.2)
elseif(SCENE STREQUAL "parachute")
  set(mode --intro-shot)
  set(time 10)
elseif(SCENE STREQUAL "pullback")
  set(mode --intro-shot)
  set(time 23.9)
elseif(SCENE STREQUAL "early")
  set(time 1)
elseif(SCENE STREQUAL "cloud")
  set(time 120)
elseif(SCENE STREQUAL "mature")
  set(time 480)
elseif(SCENE STREQUAL "fixed")
  set(time 240)
  set(extra --fixed-camera)
elseif(SCENE STREQUAL "preset2")
  set(time 60)
  set(preset 2)
endif()
set(output "${OUTPUT_DIR}/smoke-${SCENE}.png")
# A non-power-of-two grid and odd framebuffer exercise mip reduction and resize.
execute_process(COMMAND "${TSAR}" --preset ${preset} --grid 24 --iters 8
  --steps 48 --size 321 181 ${extra} ${mode} ${time} "${output}"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 110)
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Render failed (${result}):\n${stdout}\n${stderr}")
endif()
if(SCENE STREQUAL "mature" AND NOT stdout MATCHES "95.0 km wide, 64.0 km high")
  message(FATAL_ERROR "Unexpected mature visual cloud envelope: ${stdout}")
endif()
file(READ "${output}" signature LIMIT 8 HEX)
file(SIZE "${output}" bytes)
if(NOT signature STREQUAL "89504e470d0a1a0a" OR bytes LESS 100)
  message(FATAL_ERROR "Missing or invalid PNG: ${output}")
endif()
message(STATUS "${stdout}")
