set(time 0)
set(preset 1)
if(SCENE STREQUAL "early")
  set(time 1)
elseif(SCENE STREQUAL "cloud")
  set(time 120)
elseif(SCENE STREQUAL "mature")
  set(time 480)
elseif(SCENE STREQUAL "preset2")
  set(time 60)
  set(preset 2)
endif()
set(output "${OUTPUT_DIR}/smoke-${SCENE}.png")
# A non-power-of-two grid and odd framebuffer exercise mip reduction and resize.
execute_process(COMMAND "${TSAR}" --preset ${preset} --grid 24 --iters 8
  --steps 48 --size 321 181 --shot ${time} "${output}"
  RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 110)
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Render failed (${result}):\n${stdout}\n${stderr}")
endif()
file(READ "${output}" signature LIMIT 8 HEX)
file(SIZE "${output}" bytes)
if(NOT signature STREQUAL "89504e470d0a1a0a" OR bytes LESS 100)
  message(FATAL_ERROR "Missing or invalid PNG: ${output}")
endif()
message(STATUS "${stdout}")
